version: '3.1'

services:
  spdb:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  spmq:
    image: redis:alpine
    restart: always
    ports:
    - 6379:6379
